"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          pathName !== "/about/aboutstudent" && <h1>This is Navbar</h1>
        }
        {children}
      </body>
    </html>
  );
}
